### PR TITLE
Fix/2318 error in browser console

### LINKED ISSUE #2318: Vue errors in console when creating new reciep from scratch
**Description**
A bug in the Vue compoenets causing errors in browser logs.

**Reproduction**
1. Just create a new recipe

**Expected behavior**
No error are logged

**Actual behavior**
Error (see screenshot)

**Screenshots**
Screenshot_20240520_140718

**Browser**
Which browser are you using? Firefox

**Versions**
Nextcloud server version: 28
Cookbook version: master/0.11.0
Database system: MariaDB

### PR DESCRIPTION
**Pull request by christianlupus**
## Topic and Scope

Closes #2318 

## Concerns/issues

_Is the PR potentially cause any issues that might be of interest? Any other issues to be tought of?_

## Formal requirements

There are some formal requirements that should be satisfied. Please mark those by checking the corresponding box.

- [x] I did check that the app can still be opened and does not throw any browser logs
- [x] I created tests for newly added PHP code (check this if no PHP changes were made)
- [x] I updated the OpenAPI specs and added an entry to the API changelog (check if API was not modified)
- [x] I notified the matrix channel if I introduced an API change

### CODE REVIEW

File: src/components/RecipeEdit.vue [hunk 1]
```diff
@@ -528,7 +528,7 @@ const initEmptyRecipe = () => {
     // this.nutrition = {}
     recipe.value = {
         id: 0,
-        name: null,
```
Comment (christianlupus) [inline src/components/RecipeEdit.vue:531]: @seyfeb this line comes from you. I have not found any side effects but maybe you want to have a look here, though.
