### PR TITLE
Trim multiple whitespace characters when pasting

### LINKED ISSUE #713: Multiple whitespaces should be trimmed when pasting
**Description**
When copy&pasting a recipe, sometimes there are additional whitespaces added. These should be trimmed.

**Reproduction**
1. Go to e.g. [this page](https://www.gutekueche.at/schweinemedaillons-aus-dem-sous-vide-rezept-28593)
2. Copy the list of ingredients
3. Go to the cookbook app, create a new recipe
4. Add a ingredient and paste the clipboard there

**Expected behavior**
The ingredients are added one-by-one as ingredients. The (original) table structure should be broken apart.

**Actual behavior**
The table is transformed into a tab sequence. The tabs (or any adjacent spaces in general) should be trimmed. 

The same effect holds true for the instructions (and potentially the tools).

**Browser**
Firefox 88.0 under Firefox

**Versions**
Nextcloud server version: 21.0.1
Cookbook version: 0.8.4 (appstore)
Database system: MariaDB

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Fixes #713 

Now, when multiple whitespace characters appear when pasting recipe ingredients, instructions, etc. they are replace by a single space.

image

### CODE REVIEW

File: src/components/EditInputGroup.vue [hunk 1]
```diff
@@ -228,6 +228,14 @@ export default {
                 inputLinesArray[i] = inputLinesArray[i].slice(prefixLength)
             }
 
+            // Replace multiple whitespace characters with a single space
+            // This has to be applied to each item in the list if we don't want
+            // to accidentally replace all newlines with spaces before splitting
+            // Fixes #713
+            for (let i = 0; i < inputLinesArray.length; ++i) {
+                inputLinesArray[i] = inputLinesArray[i].replaceAll(/\s+/g, " ")
```
Comment (christianlupus) [inline src/components/EditInputGroup.vue:236]:
```suggestion
                inputLinesArray[i] = inputLinesArray[i].replaceAll(/\s+/g, " ").trim()
```

**Review by christianlupus — COMMENTED** [review]
I suggest to trim each line additionally. Let's have the example to paste:
```
   100 g     Reis
    50 ml    Wasser
     1 Prise Salz
```
This will cause a single space before the 2nd and 3rd row.

**Review by christianlupus — APPROVED** [review]
Seems good to me. LGTM
